export const LIST_IS_LOADING = "LIST_IS_LOADING";
export const FETCH_LIST_SUCCESS = "FETCH_LIST_SUCCESS";
export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const ENQUETE_FETCHING_LIST_SUCCESS = "ENQUETE_FETCHING_LIST_SUCCESS";
export const ENQUETE_FETCHING_LIST_FAILURE = "ENQUETE_FETCHING_LIST_FAILURE";
export const ENQUETE_FETCHING_LIST_LOADING = "ENQUETE_FETCHING_LIST_LOADING";

export const RESPOSTA_FETCHING_LIST_SUCCESS = "RESPOSTA_FETCHING_LIST_SUCCESS";
export const RESPOSTA_FETCHING_LIST_FAILURE = "RESPOSTA_FETCHING_LIST_FAILURE";
export const RESPOSTA_FETCHING_LIST_LOADING = "RESPOSTA_FETCHING_LIST_LOADING";
export const ENQUETE_TOTAL_FETCHING_LIST_SUCCESS = "ENQUETE_TOTAL_FETCHING_LIST_SUCCESS";

